"""add machine id

Revision ID: 57ccaf3ce226
Revises: 815e63192bc9
Create Date: 2025-12-24 06:19:12.197502

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "57ccaf3ce226"
down_revision: Union[str, Sequence[str], None] = "815e63192bc9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
