"""add machine id

Revision ID: a511abc5d2ca
Revises: 57ccaf3ce226
Create Date: 2025-12-24 06:25:57.908551

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a511abc5d2ca"
down_revision: Union[str, Sequence[str], None] = "57ccaf3ce226"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("machine", sa.Column("device_id", sa.String(), nullable=True))
    op.create_index(op.f("ix_machine_device_id"), "machine", ["device_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_machine_device_id"), table_name="machine")
    op.drop_column("machine", "device_id")
    # ### end Alembic commands ###
